### PR TITLE
Add Nullkiller AI support

### PR DESCRIPTION
**Pull request by nullkiller**
Fixed android build
Updated gradle
Added NKAI and switcher

### CODE REVIEW

**Comment by Nordsoft91** [comment]
What remains to support QT launcher?

**Comment by nullkiller** [comment]
> What remains to support QT launcher?

I do not know. It will need rework. QT has article how to port existing QT to Android. It says QT Creator or whatever will itself create all wrapping code, configure gradle etc.

**Comment by nullkiller** [comment]
Somebody just have to try)

**Comment by nullkiller** [comment]
I think it took Kambala a lot of time to port iOS, I do not expect this one will be much simpler so some problems are already solved.

**Comment by kambala-decapitator** [comment]
I can try, at least have some Qt+android experience

**Review by kambala-decapitator — APPROVED** [review]
not an android guy, but seems sane

@nullkiller you've made runtime test, haven't you?

**Comment by nullkiller** [comment]
Yes sure. Both AI work and switcher as well

**Pull request merged**
